language: node_js
sudo: false

## Travis CI creates empty cache directories: delete them!
install:
  - find . -maxdepth 1 -type d -empty -delete

## Travis CI caches also on filed build: Error hard!
script:
  - npm run build || exit 42

before_cache:
  - rm -f node_modules/grunt-newer/.cache/eslint/target/timestamp

cache:
  directories:
    - node_modules/
    - bower_components/